version: "3.8"

services:

  jupyterlab:
    build:
      context: .
      dockerfile: ./jupyterlab/dockerfile
      target: jupyterlab
    # update port here and below if needed
    command: jupyter retro --ip=0.0.0.0 --port=8888 --allow-root --no-browser --notebook-dir /tmp
    expose:
      - "8888"
    ports: # host port:container port
      - "8888:8888"
    volumes:
      - ./:/tmp

  binaries:
    build:
      context: .
      dockerfile: ./jupyterlab/dockerfile
      target: binaries

  forge:
    build:
      context: .
      dockerfile: ./jupyterlab/dockerfile
      target: forge
