name: test

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: build
        run: |
          docker compose up --build --no-start jupyterlab
